name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install uv
      run: |
        pip install uv

    - name: Generate slides
      run: uv run python3 generate_slides.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        # CNAME: example.com # Uncomment and replace with your custom domain if you have one
        # publish_branch: gh-pages # Default is gh-pages, but you can specify a different branch
